version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore AutoEquality\AutoEquality\AutoEquality.sln
build:
  verbosity: minimal
test:
  assemblies:
    only:
    - '**\AutoEquality.Tests.dll'
deploy:
- provider: NuGet
  api_key:
    secure: mz2Md18V4SvLjudum8Il2cTPAw6sg5gk5vvbCjhkgiDSimLGww3xBSFqHTHol0Zs
  skip_symbols: false
  on:
    branch: master
    appveyor_repo_tag: true