version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

assembly_info:
  patch: true
  file: '**\AutoEquality\Properties\AssemblyInfo.*'
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)
  
before_build:
- cmd: nuget restore AutoEquality\AutoEquality\AutoEquality.sln

build:
  verbosity: minimal
  
test:
  assemblies:
    only:
    - '**\AutoEquality.Tests.dll'

deploy:  
- provider: NuGet
  api_key:
    secure: mz2Md18V4SvLjudum8Il2cTPAw6sg5gk5vvbCjhkgiDSimLGww3xBSFqHTHol0Zs
  on:
    appveyor_repo_tag: true
