version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

before_build:
- cmd: nuget restore AutoEquality\AutoEquality\AutoEquality.sln

build:
  verbosity: minimal
  
test:
  assemblies:
    only:
    - '**\AutoEquality.Tests.dll'
deploy:  
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: NuGet
  api_key:
    secure: mz2Md18V4SvLjudum8Il2cTPAw6sg5gk5vvbCjhkgiDSimLGww3xBSFqHTHol0Zs
  on:
    appveyor_repo_tag: true
