version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

dotnet_csproj:
  patch: true
  file: '**\AutoEquality.csproj'
  version: '{appveyor_build_version}'
  package_version: '{appveyor_build_version}'
  assembly_version: '{appveyor_build_version}'
  
before_build:
- cmd: nuget restore AutoEquality\AutoEquality\AutoEquality.sln

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  
test:
  assemblies:
    only:
    - '**\AutoEquality.Tests.dll'

deploy:  
- provider: NuGet
  api_key:
    secure: mz2Md18V4SvLjudum8Il2cTPAw6sg5gk5vvbCjhkgiDSimLGww3xBSFqHTHol0Zs
  on:
    appveyor_repo_tag: true
